version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysql
#      MYSQL_USER: root
#      MYSQL_PASSWORD: password
      MYSQL_TEST_DATABASE: gotest
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: '--default-authentication-plugin=mysql_native_password'

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_REGION: ${AWS_BUCKET_REGION}
    command: ["/app/wait-for-it.sh", "db:3306", "--", "go", "run", "."]

#  minio:
#    image: quay.io/minio/minio
#    volumes:
#      - ./minio_data:/data
#    ports:
#      - "9000:9000"
#      - "9090:9090"
#    environment:
#      MINIO_ROOT_USER: ROOTUSER
#      MINIO_ROOT_PASSWORD: CHANGEME123
#    command: server /data --console-address ":9090"
#    depends_on:
#      - backend

volumes:
  db_data:
#  minio_data:
