version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # 可自行修改
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TEST_DATABASE: gotest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: '--default-authentication-plugin=mysql_native_password'

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    command: ["/app/wait-for-it.sh", "db:3306", "--", "go", "run", "."]

volumes:
  db_data:
